"""stored_hashed_passwords

Revision ID: 9137785b9572
Revises: d826fdab049f
Create Date: 2025-12-31 23:23:40.290106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9137785b9572'
down_revision: Union[str, Sequence[str], None] = 'd826fdab049f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('salt', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('iterations', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'iterations')
    op.drop_column('users', 'salt')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
