"""friend_request_unique_constraint

Revision ID: 995e4a3dbc7a
Revises: d1bc56622506
Create Date: 2026-01-01 21:55:52.809095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995e4a3dbc7a'
down_revision: Union[str, Sequence[str], None] = 'd1bc56622506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
